# name: Deploy UpdatdLambdas to AWS
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: npm run build-deploy